FROM golang:1.23-alpine

WORKDIR /app
RUN apk add --no-cache git curl
RUN go install github.com/air-verse/air@v1.61.1

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN mkdir -p /app/uploads /app/tmp

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
